// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proiectDAW.DAL;

namespace proiectDAW.DAL.Migrations
{
    [DbContext(typeof(proiectDbContext))]
    [Migration("20220114211643_AddedTables")]
    partial class AddedTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("proiectDAW.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PopularityScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.DIYIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PresentationVideoId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DIYIdeas");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.IdeaMaterial", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.Property<int>("NoPieces")
                        .HasColumnType("int");

                    b.HasKey("MaterialId", "IdeaId");

                    b.HasIndex("IdeaId");

                    b.ToTable("MaterialsDIYIdeas");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuyFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.PresentationVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DIYIdeaId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DIYIdeaId")
                        .IsUnique();

                    b.ToTable("PresentationVideos");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.DIYIdea", b =>
                {
                    b.HasOne("proiectDAW.DAL.Entities.Category", "Category")
                        .WithMany("DIYIdeas")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.IdeaMaterial", b =>
                {
                    b.HasOne("proiectDAW.DAL.Entities.DIYIdea", "DIYIdea")
                        .WithMany("MaterialsDIYIdeas")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proiectDAW.DAL.Entities.Material", "Material")
                        .WithMany("MaterialsDIYIdeas")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DIYIdea");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.PresentationVideo", b =>
                {
                    b.HasOne("proiectDAW.DAL.Entities.DIYIdea", "DIYIdea")
                        .WithOne("PresentationVideo")
                        .HasForeignKey("proiectDAW.DAL.Entities.PresentationVideo", "DIYIdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DIYIdea");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.Category", b =>
                {
                    b.Navigation("DIYIdeas");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.DIYIdea", b =>
                {
                    b.Navigation("MaterialsDIYIdeas");

                    b.Navigation("PresentationVideo");
                });

            modelBuilder.Entity("proiectDAW.DAL.Entities.Material", b =>
                {
                    b.Navigation("MaterialsDIYIdeas");
                });
#pragma warning restore 612, 618
        }
    }
}
